import re
import json
from collections import Counter

def parse_schedules():
    with open("extracted_text.txt", "r", encoding="utf-8") as f:
        content = f.read()
    
    pages = content.split("--- PAGE ")
    print(f"Total pages to parse: {len(pages) - 1}")
    
    parsed_entries = []
    failed_pages = []
    
    # State line regex, e.g., "Nebraska HS", "Wisconsin MS", "Georgia HS"
    # FBLA states can have multiple words, e.g. "North Carolina HS", "Puerto Rico HS"
    state_re = re.compile(r'^([A-Za-z\s]+)\s+(HS|MS)$')
    time_re = re.compile(r'\b(\d{1,2}:\d{2}\s*(?:AM|PM))\b', re.IGNORECASE)
    
    for page_idx, page in enumerate(pages[1:], start=1):
        lines = [l.strip() for l in page.split("\n")]
        # Remove empty lines
        lines = [l for l in lines if l]
        if not lines:
            continue
            
        # Parse Page Header
        event_when = "Unknown"
        event_time_range = "Unknown"
        event_name = "Unknown"
        event_location = "Unknown"
        
        # We search for header elements in the first few lines
        # Page headers are typically:
        # Line 0: page number (e.g. "2 ---" or just "2")
        # Line 1: Event When: Tuesday - June 30
        # Line 2: 8:30 AM - 12:30 PM
        # Line 3: Event Schedule
        # Line 4: Event Name ...
        # Line 5: PresentationArrival Location: Stars at Night
        # Line 6: 2026 NLC Registration (FBLA Middle/High School)
        # Line 7: Generated by Blue Panda...
        
        header_end_idx = 0
        for i, line in enumerate(lines[:12]):
            if "Event When:" in line:
                event_when = line.replace("Event When:", "").strip()
            elif "Event Schedule" in line:
                # Event name is the next lines
                name_parts = []
                j = i + 1
                while j < len(lines) and "Registration" not in lines[j] and "Location:" not in lines[j]:
                    name_parts.append(lines[j])
                    j += 1
                event_name = " ".join(name_parts).strip()
                
                # Check if there is location in the next lines
                if j < len(lines) and "Location:" in lines[j]:
                    loc_line = lines[j]
                    if "Arrival Location:" in loc_line:
                        parts = loc_line.split("Arrival Location:")
                        if len(parts) > 1:
                            event_location = parts[1].strip()
                            # If the event name was cut off before Arrival Location, append the left side
                            if parts[0].strip() and parts[0].strip() not in event_name:
                                event_name = (event_name + " " + parts[0].strip()).strip()
                    elif "Location:" in loc_line:
                        parts = loc_line.split("Location:")
                        event_location = parts[1].strip()
                        if parts[0].strip() and parts[0].strip() not in event_name:
                            event_name = (event_name + " " + parts[0].strip()).strip()
                header_end_idx = max(header_end_idx, j)
            elif "Arrival Time" in line:
                header_end_idx = max(header_end_idx, i)
        
        # Clean up event name
        # Remove trailing hyphens or dashes
        event_name = re.sub(r'\s*-\s*$', '', event_name).strip()
        event_name = re.sub(r'\s*-\s*Prelim\s*-\s*Section\s*\d+\s*-\s*$', '', event_name).strip()
        event_name = re.sub(r'\s*-\s*Section\s*\d+\s*-\s*$', '', event_name).strip()
        
        # Let's find state lines in the page (excluding header)
        data_lines = lines[header_end_idx + 1:]
        
        # Find indices of state lines in lines list
        state_indices = []
        for idx, line in enumerate(lines):
            if idx <= header_end_idx:
                continue
            # Check if it matches state line
            if state_re.match(line):
                state_indices.append(idx)
                
        # Now parse each entry
        for i, state_idx in enumerate(state_indices):
            # School name is the line before state
            school_idx = state_idx - 1
            if school_idx < 0:
                continue
            school_name = lines[school_idx]
            
            state_match = state_re.match(lines[state_idx])
            state_name = state_match.group(1).strip()
            division = state_match.group(2).strip()
            
            # Competitors and times are between state_idx + 1 and the next school_idx
            next_school_idx = state_indices[i+1] - 1 if i + 1 < len(state_indices) else len(lines)
            
            raw_detail_lines = lines[state_idx + 1 : next_school_idx]
            
            competitors = []
            arrival_time = None
            
            for d_line in raw_detail_lines:
                d_line_clean = d_line.strip()
                if not d_line_clean or d_line_clean == "BREAK":
                    continue
                
                # Check for times
                t_match = time_re.search(d_line_clean)
                if t_match:
                    arrival_time = t_match.group(1).strip()
                    # Strip the time from the name line
                    name_part = d_line_clean.replace(arrival_time, "").strip()
                    if name_part:
                        # Sometimes multiple names could be separated or just one
                        # If there's name left, add it
                        competitors.append(name_part)
                else:
                    # It's a competitor name
                    # Let's filter out headers that might have slipped into data_lines (e.g. Blue Panda generated footer)
                    if "Generated by Blue Panda" in d_line_clean or "2026 NLC Registration" in d_line_clean or "Arrival Time" in d_line_clean:
                        continue
                    competitors.append(d_line_clean)
            
            parsed_entries.append({
                "page": page_idx,
                "event_name": event_name,
                "event_when": event_when,
                "event_location": event_location,
                "school_name": school_name,
                "state": state_name,
                "division": division,
                "competitors": competitors,
                "arrival_time": arrival_time
            })
            
    print(f"Parsed {len(parsed_entries)} total competitor entries.")
    
    # Print sample entries
    print("\n--- SAMPLE ENTRIES ---")
    for entry in parsed_entries[:10]:
        print(entry)
        
    # Print some stats
    print("\n--- STATS ---")
    states_count = Counter([e["state"] for e in parsed_entries])
    divisions_count = Counter([e["division"] for e in parsed_entries])
    events_count = Counter([e["event_name"] for e in parsed_entries])
    schools_count = Counter([e["school_name"] for e in parsed_entries])
    
    print(f"Unique States: {len(states_count)}")
    print(f"Unique Events: {len(events_count)}")
    print(f"Unique Schools: {len(schools_count)}")
    print("Divisions:", dict(divisions_count))
    print("Top 5 States:", states_count.most_common(5))
    print("Top 5 Events:", events_count.most_common(5))
    
    # Check for anomalies, e.g. school name is a time or empty
    anomalies = [e for e in parsed_entries if not e["school_name"] or re.match(r'^\d', e["school_name"]) or "Blue Panda" in e["school_name"]]
    print(f"Number of anomalies: {len(anomalies)}")
    if anomalies:
        print("Sample anomalies:")
        for a in anomalies[:5]:
            print(a)

if __name__ == "__main__":
    parse_schedules()
